# 自动部署监控客户端
# from_node : 监控服务器 配置默认值
# src_path : 监控服务器上 监控客户端路径 配置默认值
# device ： 需要重新部署的节点 从报警信息中获取
# exporter_tar_name : 监控客户端压缩包名字 配置默认值
# exporter_name : 监控客户端名字 配置默认值
 
---
- hosts: "{{ from_node }}"
  remote_user: root
  gather_facts: F
  serial: 32
  tasks:
    # t1 拷贝到ansible所在服务器
    - name: fetch file
      fetch:
        src: "{{ src_path }}"
        dest: /usr/local/ars/ansible-runner-service/samples/exporters/
        flat: yes

- hosts: "{{ device_ssh_ip }}"
  remote_user: root
  gather_facts: F
  serial: 32
  tasks:
    # t1 再被控节点创建目录
    - name: create dir
      file:
        path: /opt/thsre/exporters
        state: directory
        owner: root
        group: root
        mode: u=rwX,g=rwX,o=rX

    # t2 把压缩包拷贝到远程主机并解压
    - name: copy tar file
      unarchive:
        src: /usr/local/ars/ansible-runner-service/samples/exporters/{{ exporter_tar_name }}
        dest: /opt/thsre/exporters
        mode: u=rwX,g=rX,o=rX
        #backup: yes
        remote_src: no

    # t3 部署服务
    - name: copy service file
      copy:
        src: /opt/thsre/exporters/{{ exporter_name }}/{{ exporter_name }}.service
        dest: /usr/lib/systemd/system/{{ exporter_name }}.service
        remote_src: yes
    
    # t4 relaod 服务
    - name: systemctl daemon-reload
      command: systemctl daemon-reload
      
    # t4 启动服务
    - name: start service
      service:
        name: "{{ exporter_name }}"
        state: started
        enabled: yes
    
    # t5 重启服务
    - name: restart service
      service: 
        name: "{{ exporter_name }}"
        state: restarted
        enabled: yes
