- hosts: 89.72.100.1
  gather_facts: False
  tasks:
    - name: sinfo_reason
      shell: |
        sinfo -R  -n "{{ nodelist }}"
      register: result
    - debug:
        msg: "{{ result.stdout_lines }}"
