- hosts:  89.72.100.1
  gather_facts: false
  tasks:
    # 用户登录错误解锁
    - name:
      shell: |
        ssh "{{ node }}" pam_tally2 -r -u {{ user }} 
      register: result
    - debug:
        msg: "{{ result.stdout_lines }}"
