- hosts: all
  user: root
  gather_facts: false
  tasks:
    - name:
      shell: |
        zpool offline "{{ ost }}" "{{ jbod }}"
      register: result
    - debug:
        msg: "{{ result.stdout_lines }}"