# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRagS2C = channel.unary_unary(
                '/RagService/GetRagS2C',
                request_serializer=rag__pb2.RagRequest.SerializeToString,
                response_deserializer=rag__pb2.RagReply.FromString,
                _registered_method=True)
        self.GetRagContent = channel.unary_unary(
                '/RagService/GetRagContent',
                request_serializer=rag__pb2.RagRequest_v2.SerializeToString,
                response_deserializer=rag__pb2.RagReply.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRagS2C(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRagS2C': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagS2C,
                    request_deserializer=rag__pb2.RagRequest.FromString,
                    response_serializer=rag__pb2.RagReply.SerializeToString,
            ),
            'GetRagContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagContent,
                    request_deserializer=rag__pb2.RagRequest_v2.FromString,
                    response_serializer=rag__pb2.RagReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRagS2C(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagService/GetRagS2C',
            rag__pb2.RagRequest.SerializeToString,
            rag__pb2.RagReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagService/GetRagContent',
            rag__pb2.RagRequest_v2.SerializeToString,
            rag__pb2.RagReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
