# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\"+\n\nRagRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x03(\t\"\x1e\n\rRagRequest_v2\x12\r\n\x05query\x18\x01 \x01(\t\"\x1b\n\x08RagReply\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t2]\n\nRagService\x12#\n\tGetRagS2C\x12\x0b.RagRequest\x1a\t.RagReply\x12*\n\rGetRagContent\x12\x0e.RagRequest_v2\x1a\t.RagReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAGREQUEST']._serialized_start=13
  _globals['_RAGREQUEST']._serialized_end=56
  _globals['_RAGREQUEST_V2']._serialized_start=58
  _globals['_RAGREQUEST_V2']._serialized_end=88
  _globals['_RAGREPLY']._serialized_start=90
  _globals['_RAGREPLY']._serialized_end=117
  _globals['_RAGSERVICE']._serialized_start=119
  _globals['_RAGSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
